export default {
    OPEN_CONFIGURATOR: 'OPEN_CONFIGURATOR',
    LOAD_TASKS: 'LOAD_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    EDIT_TASK: 'EDIT_TASK'
}